name: Build and Test (jazzy)

# Controls when the action will run.
on:
  # Triggers the workflow on push
  push:
    branches: [ jazzy-ci-test ]

  # Triggers the workflow on pull requests
  pull_request:
    branches: [ jazzy ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The runner will be ubuntu-latest, with a clean ubuntu noble container
    runs-on: ubuntu-latest
    container:
      image: ubuntu:noble

    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          # The testing repository will be used
          use-ros2-testing: true
      - uses: ijnek/action-ros-ci@jazzy
        with:
          target-ros2-distro: jazzy
